name: Publish Container

on:
  push:
    tags:
      - "disabled"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: container
  cancel-in-progress: false

env:
  DEV_BUILD: ${{ github.ref_name == 'main' }}
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Container needs to be able to read repo and publish packages.
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache: yarn
          node-version: 20
      - run: yarn install --immutable

      - name: Build application
        run: |
          yarn build

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
