name: Release

on:
  push:
    tags:
      - "v*"

concurrency: release

env:
  DEV_BUILD: false
  # renovate: datasource=docker depName=node versioning=node
  NODE_VERSION: "20.17.0"

jobs:
  versions:
    name: Versions
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Determine versions
        run: echo "RELEASE_VERSION=$(node .scripts/release-version.cjs)" >> $GITHUB_ENV

  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-nodejs-oci.yml@main
    with:
      artifact-contents: |
        output/
        package.json

  release:
    name: 🔹 Publish
    needs:
      - qa
      - versions
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      pages: write
      pull-requests: read
      security-events: write
    uses: oliversalzburg/workflows/.github/workflows/publish-oci.yml@main
    with:
      artifact-name: build-output
      context: .
      image-description: Updates CloudFlare DNS with IP addresses of running Docker containers.
      image-name: ${{ github.repository }}
      image-tag: v${{ needs.versions.outputs.RELEASE_VERSION }}
      image-title: docker-cloudflare-dns
      is-latest: true
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
