name: QA

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Lint ESLint
        run: yarn lint:eslint
      - name: Lint TSC
        run: yarn lint:tsc
      - name: Build
        run: yarn build
